############## Global settings ##############
n_process: 16
skip: True

############## Path prefix ##############
# dataset_root is root_candidates[dataset_name]
root_candidates:
  objaverse: /mnt/disk0/objaverse
  customized: /mnt/disk0/objaverse

# output folder of processed data
processed_folder: processed_data

############## Tasks ##############
tasks:
  _clean_all:
    input_path: mesh/raw.obj  
    clean_path: ./