############## Global settings ##############
n_process: 16
skip: True

############## Path prefix ##############
# dataset_root is root_candidates[dataset_name]
root_candidates:
  objaverse: /mnt/disk0/objaverse
  customized: /mnt/disk0/objaverse

# output folder of processed data
processed_folder: processed_data

############## Tasks ##############
tasks:
  # mesh 
  _normalize:
    input_path: mesh/raw.obj
    output_path: mesh/normalized.obj

  _coacd:
    input_path: mesh/normalized.obj
    output_path: mesh/coacd.obj
    delete_input: True

  _export_urdf: 
    input_path: mesh/coacd.obj
    output_path: urdf/coacd.urdf

  _manifold:
    input_path: mesh/coacd.obj
    output_path: mesh/manifold.obj

  _simplify:
    input_path: mesh/manifold.obj
    output_path: mesh/simplified.ply  # NOTE: this must be a ply
    vert_num: 2000
    gradation: 1.5    # This is recommanded in official repo
    delete_input: True

  _remove_useless:
    input_path: mesh/smooth_simplified.ply
    output_path: mesh/smooth_simplified.ply  
    delete_input: True

  _change_mesh_format: 
    input_path: mesh/simplified.ply
    output_path: mesh/simplified.obj  
    delete_input: True

  # info
  _get_basic_info:
    input_path: mesh/simplified.obj
    output_path: info/simplified.json

  # _get_tabletop_pose: 
  #   input_path: mesh/simplified.obj
  #   output_path: info/tabletop_pose.json

  # point clouds
  _get_complete_pc: 
    input_path: mesh/simplified.obj
    output_path: point_clouds/complete.npy
    point_num: 4096

  # _render_partial_pc: 
  #   input_path: mesh/simplified.obj
  #   output_path: point_clouds/kinect_partial

  # splits
