1-export_mjcf: 
  input_path: ${data.output_template}/mesh/coacd.obj
  export_mesh: False
  output_path: ${data.output_template}/urdf/coacd.xml

1-get_tabletop_pose:
  input_path: ${data.output_template}/urdf/coacd.xml
  output_path: ${data.output_template}/info/tabletop_pose.json
  # debug_vis_path: ${data.output_template}/info/debug/pose.gif # Very slow!
  max_try_num: 20    # 20 is already large enough for non-duplicated poses
  remove_duplicated: True