gpu_lst: [0,1,2,3]
thread_per_gpu: 10

scene_cfg_path: ${data.output_template}/scene_cfg/**/**.npy
max_point_num: 4096

save_path: ${data.output_vision_template}
save_pc: True
save_rgb: False
save_depth: False